version: '3.7'
services:
  dashboard:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    networks:
      - nginx.docker
  api-server:
    networks:
      - nginx.docker

networks:
  nginx.docker:
    name: nginx.docker
    external: true
