version: '3.7'
services:
  dashboard:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
      - "35729:35729"
  api-server:
    ports:
      - "8080:8080"
