# This workflow automatically bumps the repos patch version
# If you include #major, #minor or #patch in your commit-message, the workflow
# will update the version based on this input

name: Github Tag Action
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - id: tagbump
        name: "Bump version and push tag"
        uses: "anothrNick/github-tag-action@1.34.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          WITH_V: true
          RELEASE_BRANCHES: develop
          DEFAULT_BUMP: patch
      - name: "Create Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.tagbump.outputs.tag }}"
          prerelease: false
